### ISSUE TITLE
Issue with Istio in OCP 

### ISSUE THREAD

**Issue by jfbourner** [WorkloadAutomation/ibm-workload-automation-docker-compose#9]
Hi, 
I am in the process of implementing LWA in OCP. 
The issue we have, when using ISTIO, is that the agent runs on port (31114), but istio is exposed via port 32443. 
When the agent spins up and connects to the MDM, it tells the MDM it is available on 31114, but in reality this is impossible without nodeport or getting something in between to convert the ports. 

It would be good if there was an option to set the port that gets sent to the MDM. 

Any guidance would be much appreciated.

**Comment by fmossott** [comment]
Hi,
even if currently there is no official support for ISTIO, we are happy to help you on that.
My understanding is that you are trying to install a dynamic agent on OCP with ISTIO and connect it to an Maester installed outside OCP.

We provide an [helm chart](https://github.com/WorkloadAutomation/ibm-workload-automation-chart) and an [operator](https://www.ibm.com/docs/en/workload-automation/9.5.0?topic=SSGSPN_9.5.0/ReadmeCloudPak_Operator.htm) to install our agents and servers on OCP (the chart is for any Kubernetes environment).
They do not support ISTIO, but the chart is open source and you can modify it for your specific needs, this would be my recommendation. Although, If you are looking to just create OCP resources and you don't want to deal with Helm, you can just see at the resources created by the chart.

From a connectivity perspective, we configure the agent in K8s or OCP enabling the gateway component, in this way the connections are only from the agent to the master and there is no connection back from the master to the agent, that simplifies the configuration and should solve the issue you are facing. The workstation definition is still created with a port, but this is never used and you can actually not expose the agent port outside the OCP cluster.

About the connection from the agent to the server, be aware that currently the agent authenticates to the master using a client certificate exchanged using TLS mutual authentication, that implies that the TLS connection cannot be terminated on any intermediate server (ISTIO, Load Balancers, reverse proxies, etc.) and you must configure those components to perform a TLS passthrough.

**Comment by jfbourner** [comment]
Hi @fmossott 

Yes, your understanding is correct. We have an MDM/DDM that runs on a normal VM and then the agents are running inside an OCP namespace. 

Annoyingly, we are not using helm charts (We are using a maven plugin 'JKUBE' to build and deploy our resources), but thats okay, we have spun up the agent already. 

Not sure I understand the below. How do you enabling the gateway component? Surely for the master to run a job on the agent it needs a connection back to the agent once the agent is running? 

```
we configure the agent in K8s or OCP enabling the gateway component, in this way the connections are only from the agent to the master and there is no connection back from the master to the agent, that simplifies the configuration and should solve the issue you are facing.
```

**Comment by fmossott** [comment]
With the Gateway running in the agent container, it performs a long polling on the master to get the request to run jobs, get joblogs or call plugins for picklists.
In this way the agent POD (actually the gateway) connects to the master to get any request and there is no need for the master to connect to the agent.

About the chart, if you cannot use helm, another option is to install our operator (that wraps the helm chart), so that you can define the deployment creating our custom resources from JKUBE. How to use the operator is included in our [doc](https://www.ibm.com/docs/en/workload-automation/10.1.0?topic=dwacrho-deploying-workload-automation-components-using-workload-automation-operator)

Another option is to get the chart locally on your machine and run a dryrun to check and copy the resources that would be created.

If you want to create K8s resources directly, consider that we usually define an headless service, a stateful set with a PVC for storing the datadir of the agent (so that you can preserve the agentID, joblog and the status of jobs to be recovered when the pod is restarted or moved), and we use secrets to store certificates. We also create RBAC definitions in order to run kubernetes jobs with our [K8s job type](https://www.yourautomationhub.io/detail/kubernetes)
You can look at the [templates](https://github.com/WorkloadAutomation/ibm-workload-automation-chart/tree/master/helm_charts/ibm-workload-automation-prod/charts/wa-dyn-agent-prod/templates) in our chart to create yours

This is an example of the StatefulSet created by the chart
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hwa-waagent
  namespace: hwa
  labels:
    app.kubernetes.io/instance: hwa
    app.kubernetes.io/name: waagent
    environment: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: hwa
      app.kubernetes.io/name: waagent
  template:
    metadata:
      creationTimestamp: null
      labels:
        affinity: wa-agent
        app.kubernetes.io/instance: hwa
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: waagent
        environment: prod
      annotations:
        productChargedContainers: All
        productID: c81f41563d584e3080bda3c5d7cef583
        productMetric: PROCESSOR_VALUE_UNIT
        productName: IBM Workload Scheduler
        productVersion: '10.1'
    spec:
      volumes:
        - name: cert-bind-volume
          secret:
            secretName: waagent-cert-secret
            defaultMode: 436
            optional: true
        - name: hwa-waagent-dyn-agent-scripts-volume
          configMap:
            name: hwa-waagent-dyn-agent-scripts
            defaultMode: 511
            optional: true
      initContainers:
        - name: init-config
          image: cp.icr.io/cp/ibm-workload-automation-agent-dynamic:10.1.0.03.F3
          command:
            - /opt/wautils/wa_populate_volume.sh
          args:
            - '-s /home/wauser -d /tmp/data'
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - name: data-hwa-waagent
              mountPath: /tmp/data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
      containers:
        - name: waagent
          image: cp.icr.io/cp/ibm-workload-automation-agent-dynamic:10.1.0.03.F3
          env:
            - name: LICENSE
              value: accept
            - name: LANG
              value: en
            - name: WA_DEBUG
              value: 'false'
            - name: AGT_NAME
              value: WA_AGT
            - name: WA_IS_KUBE
              value: 'true'
            - name: WA_DEBUG_SCRIPTS
              value: 'false'
            - name: WA_USER_ENGINE
              valueFrom:
                secretKeyRef:
                  name: hwa-waagent-secret
                  key: WA_USER_ENGINE
                  optional: true
            - name: WA_USER_ENGINE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hwa-waagent-secret
                  key: WA_USER_ENGINE_PASSWORD
                  optional: true
            - name: SSL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hwa-waagent-secret
                  key: SSL_PASSWORD
                  optional: true
            - name: WA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hwa-waagent-secret
                  key: WA_API_KEY
                  optional: true
            - name: SERVERHOSTNAME
              value: hwa-waserver
            - name: SERVERPORT
              value: '31116'
            - name: WA_JWT
              value: 'true'
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - name: data-hwa-waagent
              mountPath: /home/wauser
              subPath: wauser
            - name: cert-bind-volume
              mountPath: /opt/wautils/certs
            - name: hwa-waagent-dyn-agent-scripts-volume
              mountPath: /opt/wautils/custom_scripts
          livenessProbe:
            exec:
              command:
                - /opt/wautils/wa_probe.sh
                - agent
                - liveness
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /opt/wautils/wa_probe.sh
                - agent
                - readiness
            initialDelaySeconds: 200
            timeoutSeconds: 1
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: wauser
      serviceAccount: wauser
      securityContext:
        runAsUser: 999
        runAsNonRoot: true
        supplementalGroups:
          - 999
        fsGroup: 999
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 3
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: affinity
                      operator: In
                      values:
                        - wa-agent
                topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: data-hwa-waagent
        creationTimestamp: null
        labels:
          app.kubernetes.io/instance: hwa
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: waagent
          environment: prod
          helm.sh/chart: waagent
          release: hwa
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        volumeMode: Filesystem
      status:
        phase: Pending
  serviceName: hwa-waagent-h
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
```

P.S. Since this about K8s and not docker, I'll transfer the issue on the Helm chart project
